version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install --prefer-offline

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      # prepare directory
      - run: mkdir -p reports/junit

      # run linter!
      - run: yarn lint --format junit -o reports/junit/js-lint-results.xml

      # run tests!
      - run:
          name: "JavaScript Test Suite"
          command: yarn test:ci --runInBand
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"

      # collect coverage and test result
      - run: bash <(curl -s https://codecov.io/bash)
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit

      # build typescript
      - run: yarn build

  deploy:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm publish

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
